articles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('new/', views.new),
    path('create/', views.create),
    path('<int:article_pk>', views.detail),
    path('<int:article_pk>/delete/', views.delete),
    path('<int:article_pk>/edit/', views.edit),
    path('<int:article_pk>/update/', views.update)
]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.index, name='name'),
    path('result/', views.result, name='result'),
]

reboot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('jobs/', include('jobs.urls'))
]

articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

jobs/models.py
from django.db import models

# Create your models here.
class Job(models.Model):
    name = models.CharField(max_length=10)
    job = models.TextField()

articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    articles = Article.objects.order_by('-id')
    context = {
        'articles' : articles
    }
    return render(request, 'articles/index.html',context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    article = Article()
    article.title = request.GET.get('title')
    article.content = request.GET.get('content')
    article.created_at = request.GET.get('created_at')
    article.updated_at = request.GET.get('updated_at')
    article.save()
    return redirect(f'/articles/{article.pk}')

def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article': article
    }
    return render(request, 'articles/detail.html', context)

def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    article.delete()
    return redirect('/articles/')

def edit(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article': article
    }
    return render(request, 'articles/edit.html', context)

def update(request, article_pk):
    title = request.GET.get('title')
    content = request.GET.get('content')
    article = Article.objects.get(pk=article_pk)
    article.title = title
    article.content = content
    article.save()
    return redirect(f'/articles/{article.pk}')

jobs/views.py
from django.shortcuts import render
from .models import Job
from faker import Faker
import requests
from decouple import config

# Create your views here.
def index(request):
    return render(request, 'jobs/index.html')

def result(request):
    name = request.POST.get('name')
    try: 
        job = Job.objects.get(name=name)
    except:
        fake = Faker('en')
        job = Job.objects.create(name=name, job=fake.job())
    info = Job.objects.get(name=name)

    # 직업 결과에 따라, giphy 요청
    api_key = config('GIPHY_API_KEY')
    # 1. url 설정
    url = f'http://api.giphy.com/v1/gifs/search?api_key={api_key}&q={info.job}'
    # 2. 요청 보내기
    response = requests.get(url).json()
    # 3. 응답 결과에서 이미지 url 뽑기
    try:
        image_url = response['data'][0].get('images').get('original').get('url')
    except:
        image_url = None
    context = {
        'info': info,
        'image_url': image_url
    }
    return render(request, 'jobs/result.html', context)

articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>게시판</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <style>
    {% block css %}
    {% endblock %} 
  </style>
</head>
<body>
  <div class="pos-f-t">
    <div class="collapse" id="navbarToggleExternalContent">
      <div class="bg-dark p-4">
        <h5 class="text-white h4">Collapsed content</h5>
        <span class="text-muted">Toggleable via the navbar brand.</span>
      </div>
    </div>
    <nav class="navbar navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </nav>
  </div>
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

articles/templates/articles/detail.html
{% extends 'articles/base.html' %}
{% block body %}
  <h1> {{article.id}}번글 </h1>
  <h1> {{ article.title }} </h1>
  <h2> {{ article.content}} </h2> 
  <h3> {{ article.created_at}} </h3>
  <a href="/articles/"><button>목록으로</button></a>
  <a href="/articles/{{ article.pk }}/delete"><button>삭제</button></a>
  <a href="/articles/{{ article.pk }}/edit"><button>수정</button></a>
{% endblock %}

articles/templates/articles/edit.html
{% extends 'articles/base.html' %}
{% block css %}
edit_title {
  text-align:center;
}

edit_content {
  display:flex;
  width:500px;
  height:500px;
  background-color:antiquewhite;
  margin-bottom :20px;
  align-items: center;
  justify-content: center;
}
{% endblock %}
{% block body %}
<div class="edit_content">
  <form action="/articles/{{ article.pk }}/update/" method='GET'>
    <div class="form-group">
      <label for="formGroupExampleInput"> 제목</label>
      <input type="text" class="form-control" id="formGroupExampleInput" name="title" value="{{ article.title }}">
      <small id="emailHelp" class="form-text text-muted">글의 제목을 수정 해주세요.</small>
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">내용</label>
      <textarea name="content" class="form-control" id="exampleFormControlTextarea1" rows="3">{{ article.content }}</textarea>
    </div>
    <div>
      <button type="submit" class="btn btn-primary">글 수정</button>
    </div>
  </form>
</div>
{% endblock %}

articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% block css %}
.toptitle {
  display:flex;
}

.board_table {
  display:flex;
  width : 100wh;
}

.board_table > tbody {
  margin:10px;
}

.go_new {
  display:flex;
  width:50px;
  height:50px;
  margin:0 auto;
  text-align:center;
  line-height:50px;
}
{% endblock %}
{% block body %}
<div class="toptitle">
  <div>
    2주만에 돌아온 탁쌤의 Web시간!
  </div>
  <a class="" href="/articles/new/">
    <button class="go_new">작성
    </button>
  </a>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">제목</th>
      <th scope="col">작성일자</th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}
    <tr>
      <th scope="row">{{ article.id }}</th>
      <td>
        <a href="/articles/{{article.id}}">
          {{ article.title }}</td>
        </a>
      <td>{{ article.created_at}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

articles/templates/articles/new.html
{% extends 'articles/base.html' %}
{% block body %}
<h1>글 작성하기</h1>
<div class="edit_content">
  <form action="/articles/create/" method='GET'>
    <div class="form-group">
      <label for="formGroupExampleInput"> 제목</label>
      <input type="text" class="form-control" id="formGroupExampleInput" name="title" placeholder="제목을 입력하세요">
      <small id="emailHelp" class="form-text text-muted">글의 제목을 작성 해주세요.</small>
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">내용</label>
      <textarea class="form-control" name='content'id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
    <div>
      <button type="submit" class="btn btn-primary">글 작성</button>
    </div>
  </form>
{% endblock %}

jobs/templates/jobs/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>전생</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <style>
    {% block css %}
    {% endblock %} 
  </style>
</head>
<body>
    {% block body %}
    {% endblock %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

jobs/templates/jobs/index.html
{% extends 'jobs/base.html' %}
{% block body %}
<form action="{% url 'jobs:result' %}" method="POST">
  {% csrf_token %}
  <div class="form-row align-items-center m-2">
    <div class="col-sm-4 my-1">
      <label class="sr-only" for="inlineFormInputName">Name</label>
      <input type="text" name="name" class="form-control" id="inlineFormInputName" placeholder="이름을 입력하세요.">
    </div>
    <div class="col-auto my-1">
      <input type="submit" class="btn btn-secondary" value="전생 확인하기">
    </div>
  </div>
</form>
{% endblock %}

jobs/templates/jobs/result.html
{% extends 'jobs/base.html' %}
{% block body %}
<div class="jumbotron jumbotron-fluid text-center">
  <div class="container">
    <h1 class="display-4">{{ info.job }}</h1>
    <img src="{{ image_url }}" alt="{{ info.job }}">
    <p class="lead mt-3">{{ info.name }}님의 전생은 {{ info.job }}입니다.</p>
    <a href="/jobs/" class="btn btn-outline-secondary mt-4 mx-auto d-block" style="width:70%">다시하기</a>
  </div>
</div>
{% endblock %}